[2023-03-22T19:59:29.936-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: api_dag.is_api_active manual__2023-03-22T20:26:41.859406+00:00 [queued]>
[2023-03-22T19:59:29.942-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: api_dag.is_api_active manual__2023-03-22T20:26:41.859406+00:00 [queued]>
[2023-03-22T19:59:29.942-0400] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T19:59:29.942-0400] {taskinstance.py:1280} INFO - Starting attempt 2 of 1
[2023-03-22T19:59:29.942-0400] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T19:59:29.947-0400] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): is_api_active> on 2023-03-22 20:26:41.859406+00:00
[2023-03-22T19:59:29.949-0400] {standard_task_runner.py:55} INFO - Started process 7181 to run task
[2023-03-22T19:59:29.953-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'api_dag', 'is_api_active', 'manual__2023-03-22T20:26:41.859406+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_test.py', '--cfg-path', '/var/folders/71/zhs_yc7n05l7c97rnhn92bb80000gn/T/tmp1mmk4bsf']
[2023-03-22T19:59:29.954-0400] {standard_task_runner.py:83} INFO - Job 77: Subtask is_api_active
[2023-03-22T19:59:29.977-0400] {task_command.py:388} INFO - Running <TaskInstance: api_dag.is_api_active manual__2023-03-22T20:26:41.859406+00:00 [running]> on host sunandas-laptop.hsd1.ga.comcast.net
[2023-03-22T19:59:30.000-0400] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=is_api_active
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T20:26:41.859406+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-22T20:26:41.859406+00:00
[2023-03-22T19:59:30.001-0400] {http.py:122} INFO - Poking: weather?q=Monroe,GA,US&units=standard&appid=94ca56afa3eee20f7100985fdfe682aa
[2023-03-22T19:59:30.006-0400] {base.py:73} INFO - Using connection ID 'my_api_connection' for task execution.
[2023-03-22T20:02:46.464-0400] {local_task_job.py:272} WARNING - State of this instance has been externally set to queued. Terminating instance.
[2023-03-22T20:02:46.477-0400] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 7181. PIDs of all processes in the group: [7181]
[2023-03-22T20:02:46.477-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 7181
[2023-03-22T20:03:46.481-0400] {process_utils.py:147} WARNING - process psutil.Process(pid=7181, name='Python', status='running', started='19:59:29') did not respond to SIGTERM. Trying SIGKILL
[2023-03-22T20:03:46.481-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 7181
[2023-03-22T20:03:46.484-0400] {process_utils.py:79} INFO - Process psutil.Process(pid=7181, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='19:59:29') (7181) terminated with exit code Negsignal.SIGKILL
[2023-03-22T20:03:46.484-0400] {standard_task_runner.py:168} ERROR - Job 77 was killed before it finished (likely due to running out of memory)
