[2023-03-26T00:30:27.025-0400] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_dag.is_api_active manual__2023-03-26T04:17:00.866455+00:00 [queued]>
[2023-03-26T00:30:27.031-0400] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_dag.is_api_active manual__2023-03-26T04:17:00.866455+00:00 [queued]>
[2023-03-26T00:30:27.031-0400] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-26T00:30:27.031-0400] {taskinstance.py:1283} INFO - Starting attempt 2 of 1
[2023-03-26T00:30:27.031-0400] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-26T00:30:27.036-0400] {taskinstance.py:1303} INFO - Executing <Task(HttpSensor): is_api_active> on 2023-03-26 04:17:00.866455+00:00
[2023-03-26T00:30:27.038-0400] {standard_task_runner.py:55} INFO - Started process 36132 to run task
[2023-03-26T00:30:27.041-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'api_dag', 'is_api_active', 'manual__2023-03-26T04:17:00.866455+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_test.py', '--cfg-path', '/var/folders/71/zhs_yc7n05l7c97rnhn92bb80000gn/T/tmpgy3vd5wj']
[2023-03-26T00:30:27.042-0400] {standard_task_runner.py:83} INFO - Job 131: Subtask is_api_active
[2023-03-26T00:30:27.073-0400] {task_command.py:388} INFO - Running <TaskInstance: api_dag.is_api_active manual__2023-03-26T04:17:00.866455+00:00 [running]> on host sunandas-laptop.hsd1.ga.comcast.net
[2023-03-26T00:30:27.096-0400] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=is_api_active
AIRFLOW_CTX_EXECUTION_DATE=2023-03-26T04:17:00.866455+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-26T04:17:00.866455+00:00
[2023-03-26T00:30:27.098-0400] {http.py:122} INFO - Poking: weather?q=Atlanta,Georgia,US&units=standard&appid=94ca56afa3eee20f7100985fdfe682aa
[2023-03-26T00:30:27.102-0400] {base.py:73} INFO - Using connection ID 'my_api_connection' for task execution.
[2023-03-26T00:38:36.249-0400] {local_task_job.py:276} WARNING - State of this instance has been externally set to None. Terminating instance.
[2023-03-26T00:38:36.266-0400] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 36132. PIDs of all processes in the group: [36132]
[2023-03-26T00:38:36.266-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 36132
[2023-03-26T00:39:36.275-0400] {process_utils.py:147} WARNING - process psutil.Process(pid=36132, name='Python', status='running', started='00:30:27') did not respond to SIGTERM. Trying SIGKILL
[2023-03-26T00:39:36.277-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 36132
[2023-03-26T00:39:36.286-0400] {process_utils.py:79} INFO - Process psutil.Process(pid=36132, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='00:30:27') (36132) terminated with exit code Negsignal.SIGKILL
[2023-03-26T00:39:36.286-0400] {standard_task_runner.py:168} ERROR - Job 131 was killed before it finished (likely due to running out of memory)
