[2023-03-25T14:19:59.338-0400] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_dag.move_to_hdfs manual__2023-03-22T23:39:09.715241+00:00 [queued]>
[2023-03-25T14:19:59.342-0400] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_dag.move_to_hdfs manual__2023-03-22T23:39:09.715241+00:00 [queued]>
[2023-03-25T14:19:59.342-0400] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T14:19:59.342-0400] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-25T14:19:59.343-0400] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T14:19:59.346-0400] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): move_to_hdfs> on 2023-03-22 23:39:09.715241+00:00
[2023-03-25T14:19:59.348-0400] {standard_task_runner.py:55} INFO - Started process 9141 to run task
[2023-03-25T14:19:59.350-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'api_dag', 'move_to_hdfs', 'manual__2023-03-22T23:39:09.715241+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_test.py', '--cfg-path', '/var/folders/71/zhs_yc7n05l7c97rnhn92bb80000gn/T/tmpo6oe5gdw']
[2023-03-25T14:19:59.351-0400] {standard_task_runner.py:83} INFO - Job 103: Subtask move_to_hdfs
[2023-03-25T14:19:59.368-0400] {task_command.py:388} INFO - Running <TaskInstance: api_dag.move_to_hdfs manual__2023-03-22T23:39:09.715241+00:00 [running]> on host sunandas-laptop.hsd1.ga.comcast.net
[2023-03-25T14:19:59.384-0400] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=move_to_hdfs
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T23:39:09.715241+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-22T23:39:09.715241+00:00
[2023-03-25T14:19:59.385-0400] {subprocess.py:63} INFO - Tmp dir root location: 
 /var/folders/71/zhs_yc7n05l7c97rnhn92bb80000gn/T
[2023-03-25T14:19:59.386-0400] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/Users/sunanda/Downloads/hadoop-3.3.4/bin/hdfs dfs -put ~/Downloads/airflow/california_cities_data.csv /user/api']
[2023-03-25T14:19:59.389-0400] {subprocess.py:86} INFO - Output:
[2023-03-25T14:20:00.618-0400] {subprocess.py:93} INFO - 2023-03-25 14:20:00,617 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-03-25T14:20:01.500-0400] {subprocess.py:93} INFO - put: Call From Sunandas-Laptop.hsd1.ga.comcast.net/10.1.10.75 to localhost:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2023-03-25T14:20:01.575-0400] {subprocess.py:97} INFO - Command exited with return code 1
[2023-03-25T14:20:01.579-0400] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-03-25T14:20:01.589-0400] {taskinstance.py:1321} INFO - Marking task as FAILED. dag_id=api_dag, task_id=move_to_hdfs, execution_date=20230322T233909, start_date=20230325T181959, end_date=20230325T182001
[2023-03-25T14:20:01.593-0400] {standard_task_runner.py:100} ERROR - Failed to execute job 103 for task move_to_hdfs (Bash command failed. The command returned a non-zero exit code 1.; 9141)
[2023-03-25T14:20:01.613-0400] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-25T14:20:01.619-0400] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
