[2023-03-26T00:25:02.646-0400] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_dag.is_api_active scheduled__2023-03-25T00:00:00+00:00 [queued]>
[2023-03-26T00:25:02.656-0400] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_dag.is_api_active scheduled__2023-03-25T00:00:00+00:00 [queued]>
[2023-03-26T00:25:02.656-0400] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-26T00:25:02.656-0400] {taskinstance.py:1283} INFO - Starting attempt 5 of 1
[2023-03-26T00:25:02.656-0400] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-26T00:25:02.661-0400] {taskinstance.py:1303} INFO - Executing <Task(HttpSensor): is_api_active> on 2023-03-25 00:00:00+00:00
[2023-03-26T00:25:02.665-0400] {standard_task_runner.py:55} INFO - Started process 35760 to run task
[2023-03-26T00:25:02.667-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'api_dag', 'is_api_active', 'scheduled__2023-03-25T00:00:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_test.py', '--cfg-path', '/var/folders/71/zhs_yc7n05l7c97rnhn92bb80000gn/T/tmp3zfjjdmw']
[2023-03-26T00:25:02.668-0400] {standard_task_runner.py:83} INFO - Job 125: Subtask is_api_active
[2023-03-26T00:25:02.700-0400] {task_command.py:388} INFO - Running <TaskInstance: api_dag.is_api_active scheduled__2023-03-25T00:00:00+00:00 [running]> on host sunandas-laptop.hsd1.ga.comcast.net
[2023-03-26T00:25:02.731-0400] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=is_api_active
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-25T00:00:00+00:00
[2023-03-26T00:25:02.733-0400] {http.py:122} INFO - Poking: weather?q=Atlanta,Georgia,US&units=standard&appid=94ca56afa3eee20f7100985fdfe682aa
[2023-03-26T00:25:02.736-0400] {base.py:73} INFO - Using connection ID 'my_api_connection' for task execution.
[2023-03-26T00:29:24.981-0400] {local_task_job.py:276} WARNING - State of this instance has been externally set to queued. Terminating instance.
[2023-03-26T00:29:24.989-0400] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 35760. PIDs of all processes in the group: [35760]
[2023-03-26T00:29:24.989-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 35760
[2023-03-26T00:30:25.029-0400] {process_utils.py:147} WARNING - process psutil.Process(pid=35760, name='Python', status='running', started='00:25:02') did not respond to SIGTERM. Trying SIGKILL
[2023-03-26T00:30:25.032-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 35760
[2023-03-26T00:30:25.038-0400] {process_utils.py:79} INFO - Process psutil.Process(pid=35760, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='00:25:02') (35760) terminated with exit code Negsignal.SIGKILL
[2023-03-26T00:30:25.038-0400] {standard_task_runner.py:168} ERROR - Job 125 was killed before it finished (likely due to running out of memory)
