[2023-03-22T20:03:52.217-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: api_dag.is_api_active manual__2023-03-22T23:21:21.366461+00:00 [queued]>
[2023-03-22T20:03:52.225-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: api_dag.is_api_active manual__2023-03-22T23:21:21.366461+00:00 [queued]>
[2023-03-22T20:03:52.226-0400] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T20:03:52.226-0400] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-22T20:03:52.226-0400] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T20:03:52.232-0400] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): is_api_active> on 2023-03-22 23:21:21.366461+00:00
[2023-03-22T20:03:52.234-0400] {standard_task_runner.py:55} INFO - Started process 7485 to run task
[2023-03-22T20:03:52.237-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'api_dag', 'is_api_active', 'manual__2023-03-22T23:21:21.366461+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_test.py', '--cfg-path', '/var/folders/71/zhs_yc7n05l7c97rnhn92bb80000gn/T/tmp02t1ytdh']
[2023-03-22T20:03:52.238-0400] {standard_task_runner.py:83} INFO - Job 80: Subtask is_api_active
[2023-03-22T20:03:52.270-0400] {task_command.py:388} INFO - Running <TaskInstance: api_dag.is_api_active manual__2023-03-22T23:21:21.366461+00:00 [running]> on host sunandas-laptop.hsd1.ga.comcast.net
[2023-03-22T20:03:52.290-0400] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=is_api_active
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T23:21:21.366461+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-22T23:21:21.366461+00:00
[2023-03-22T20:03:52.291-0400] {http.py:122} INFO - Poking: weather?q=Monroe,GA,US&units=standard&appid=94ca56afa3eee20f7100985fdfe682aa
[2023-03-22T20:03:52.294-0400] {base.py:73} INFO - Using connection ID 'my_api_connection' for task execution.
[2023-03-22T20:11:45.802-0400] {local_task_job.py:272} WARNING - State of this instance has been externally set to None. Terminating instance.
[2023-03-22T20:11:45.806-0400] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 7485. PIDs of all processes in the group: [7485]
[2023-03-22T20:11:45.806-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 7485
[2023-03-22T20:12:45.835-0400] {process_utils.py:147} WARNING - process psutil.Process(pid=7485, name='Python', status='running', started='20:03:52') did not respond to SIGTERM. Trying SIGKILL
[2023-03-22T20:12:45.836-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 7485
[2023-03-22T20:12:45.841-0400] {process_utils.py:79} INFO - Process psutil.Process(pid=7485, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='20:03:52') (7485) terminated with exit code Negsignal.SIGKILL
[2023-03-22T20:12:45.841-0400] {standard_task_runner.py:168} ERROR - Job 80 was killed before it finished (likely due to running out of memory)
