[2023-03-22T16:35:15.111-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_api_connection.api_sensor scheduled__2023-03-19T00:00:00+00:00 [queued]>
[2023-03-22T16:35:15.117-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_api_connection.api_sensor scheduled__2023-03-19T00:00:00+00:00 [queued]>
[2023-03-22T16:35:15.117-0400] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T16:35:15.117-0400] {taskinstance.py:1280} INFO - Starting attempt 3 of 1
[2023-03-22T16:35:15.117-0400] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T16:35:15.127-0400] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): api_sensor> on 2023-03-19 00:00:00+00:00
[2023-03-22T16:35:15.133-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'my_api_connection', 'api_sensor', 'scheduled__2023-03-19T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/cities.py', '--cfg-path', '/var/folders/71/zhs_yc7n05l7c97rnhn92bb80000gn/T/tmp9vs4_7vy']
[2023-03-22T16:35:15.134-0400] {standard_task_runner.py:83} INFO - Job 53: Subtask api_sensor
[2023-03-22T16:35:15.140-0400] {standard_task_runner.py:55} INFO - Started process 75988 to run task
[2023-03-22T16:35:15.154-0400] {task_command.py:388} INFO - Running <TaskInstance: my_api_connection.api_sensor scheduled__2023-03-19T00:00:00+00:00 [running]> on host sunandas-laptop.local
[2023-03-22T16:35:15.172-0400] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_api_connection
AIRFLOW_CTX_TASK_ID=api_sensor
AIRFLOW_CTX_EXECUTION_DATE=2023-03-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-19T00:00:00+00:00
[2023-03-22T16:35:15.173-0400] {http.py:122} INFO - Poking: weather?q=cities,states,US&units=standard&appid=94ca56afa3eee20f7100985fdfe682aa
[2023-03-22T16:35:15.175-0400] {base.py:73} INFO - Using connection ID 'my_api_connection' for task execution.
[2023-03-22T16:35:30.249-0400] {local_task_job.py:272} WARNING - State of this instance has been externally set to queued. Terminating instance.
[2023-03-22T16:35:30.255-0400] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 75988. PIDs of all processes in the group: [75988]
[2023-03-22T16:35:30.255-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 75988
[2023-03-22T16:36:30.255-0400] {process_utils.py:147} WARNING - process psutil.Process(pid=75988, name='Python', status='running', started='16:35:15') did not respond to SIGTERM. Trying SIGKILL
[2023-03-22T16:36:30.256-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 75988
[2023-03-22T16:36:30.272-0400] {process_utils.py:79} INFO - Process psutil.Process(pid=75988, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='16:35:15') (75988) terminated with exit code Negsignal.SIGKILL
[2023-03-22T16:36:30.272-0400] {standard_task_runner.py:168} ERROR - Job 53 was killed before it finished (likely due to running out of memory)
